# Generated by Django 4.2.6 on 2023-10-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SavingsAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=20)),
                ("account_holder_name", models.CharField(max_length=100)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("interest_rate", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_transaction_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
